<?php
	$capitals=[
		 ['United Arab Emirates','Abu Dhabi']
		,['Nigeria','Abuja']
		,['Ghana','Accra']
		,['Ethiopia','Addis Ababa']
		,['Algeria','Algiers']
		,['Jordan','Amman']
		,['Netherlands','Amsterdam']
		,['Andorra','Andorra la Vella']
		,['Turkey','Ankara']
		,['Madagascar','Antananarivo']
		,['Samoa','Apia']
		,['Turkmenistan','Ashgabat']
		,['Eritrea','Asmara']
		,['Kazakhstan','Astana']
		,['Paraguay','Asunción']
		,['Greece','Athens']
		,['Iraq','Baghdad']
		,['Azerbaijan','Baku']
		,['Mali','Bamako']
		,['Brunei','Bandar Seri Begawan']
		,['Thailand','Bangkok']
		,['Central African Republic','Bangui']
		,['Gambia','Banjul']
		,['Saint Kitts and Nevis','Basseterre']
		,['China','Beijing']
		,['Lebanon','Beirut']
		,['Serbia','Belgrade']
		,['Belize','Belmopan']
		,['Germany','Berlin']
		,['Switzerland','Bern']
		,['Kyrgyzstan','Bishkek']
		,['Guinea-Bissau','Bissau']
		,['Colombia','Bogotá']
		,['Brazil','Brasilia']
		,['Slovakia','Bratislava']
		,['Republic of the Congo','Brazzaville']
		,['Barbados','Bridgetown']
		,['Belgium','Brussels']
		,['Romania','Bucharest']
		,['Hungary','Budapest']
		,['Argentina','Buenos Aires']
		,['Burundi','Bujumbura']
		,['Egypt','Cairo']
		,['Australia','Canberra']
		,['Venezuela','Caracas']
		,['Saint Lucia','Castries']
		,['Moldova','Chisinau']
		,['Guinea','Conakry']
		,['Denmark','Copenhagen']
		,['Senegal','Dakar']
		,['Syria','Damascus']
		,['Bangladesh','Dhaka']
		,['Timor-Leste','Dili']
		,['Djibouti','Djibouti (city)']
		,['Tanzania','Dodoma']
		,['Qatar','Doha']
		,['Ireland','Dublin']
		,['Tajikistan','Dushanbe']
		,['Sierra Leone','Freetown']
		,['Tuvalu','Funafuti']
		,['Botswana','Gaborone']
		,['Guyana','Georgetown']
		,['Guatemala','Guatemala City']
		,['Vietnam','Hanoi']
		,['Zimbabwe','Harare']
		,['Cuba','Havana']
		,['Finland','Helsinki']
		,['Solomon Islands','Honiara']
		,['Pakistan','Islamabad']
		,['Indonesia','Jakarta']
		,['Israel','Jerusalem']
		,['Palestine','Jerusalem (East)']
		,['South Sudan','Juba']
		,['Afghanistan','Kabul']
		,['Uganda','Kampala']
		,['Nepal','Kathmandu']
		,['Sudan','Khartoum']
		,['Rwanda','Kigali']
		,['Jamaica','Kingston']
		,['Saint Vincent and the Grenadines','Kingstown']
		,['Democratic Republic of the Congo','Kinshasa']
		,['Malaysia','Kuala Lumpur']
		,['Kuwait','Kuwait City']
		,['Ukraine','Kyiv (also known as Kiev)']
		,['Gabon','Libreville']
		,['Malawi','Lilongwe']
		,['Peru','Lima']
		,['Portugal','Lisbon']
		,['Slovenia','Ljubljana']
		,['Togo','Lomé']
		,['United Kingdom','London']
		,['Angola','Luanda']
		,['Zambia','Lusaka']
		,['Luxembourg','Luxembourg (city)']
		,['Spain','Madrid']
		,['Marshall Islands','Majuro']
		,['Equatorial Guinea','Malabo (de jure), 
		Oyala (seat of government)']
		,['Maldives','Male']
		,['Nicaragua','Managua']
		,['Bahrain','Manama']
		,['Philippines','Manila']
		,['Mozambique','Maputo']
		,['Lesotho','Maseru']
		,['Swaziland','Mbabane (administrative), 
		Lobamba (legislative, royal)']
		,['Mexico','Mexico City']
		,['Belarus','Minsk']
		,['Somalia','Mogadishu']
		,['Monaco','Monaco']
		,['Liberia','Monrovia']
		,['Uruguay','Montevideo']
		,['Comoros','Moroni']
		,['Russia','Moscow']
		,['Oman','Muscat']
		,['Chad','N\'Djamena']
		,['Kenya','Nairobi']
		,['Bahamas','Nassau']
		,['Myanmar (Burma)','Naypyidaw']
		,['India','New Delhi']
		,['Palau','Ngerulmud']
		,['Niger','Niamey']
		,['Cyprus','Nicosia']
		,['Mauritania','Nouakchott']
		,['Tonga','Nuku\ʻalofa']
		,['Norway','Oslo']
		,['Canada','Ottawa']
		,['Burkina Faso','Ouagadougou']
		,['Micronesia','Palikir']
		,['Panama','Panama City']
		,['Suriname','Paramaribo']
		,['France','Paris']
		,['Cambodia','Phnom Penh']
		,['Montenegro','Podgorica']
		,['Mauritius','Port Louis']
		,['Papua New Guinea','Port Moresby']
		,['Trinidad and Tobago','Port of Spain']
		,['Vanuatu','Port Vila']
		,['Haiti','Port-au-Prince']
		,['Benin','Porto-Novo']
		,['Czech Republic','Prague']
		,['Cabo Verde','Praia']
		,['South Africa','Pretoria (administrative), 
		Cape Town (legislative), 
		Bloemfontein (judicial)']
		,['Kosovo','Pristina']
		,['North Korea','Pyongyang']
		,['Ecuador','Quito']
		,['Morocco','Rabat']
		,['Iceland','Reykjavik']
		,['Latvia','Riga']
		,['Saudi Arabia','Riyadh']
		,['Italy','Rome']
		,['Dominica','Roseau']
		,['Grenada','Saint George\'s']
		,['Antigua and Barbuda','Saint John\'s']
		,['Costa Rica','San Jose']
		,['San Marino','San Marino']
		,['El Salvador','San Salvador']
		,['Yemen','Sana\'a']
		,['Chile','Santiago']
		,['Dominican Republic','Santo Domingo']
		,['Sao Tome and Principe','São Tomé']
		,['Bosnia and Herzegovina','Sarajevo']
		,['South Korea','Seoul']
		,['Singapore','Singapore']
		,['Macedonia (FYROM)','Skopje']
		,['Bulgaria','Sofia']
		,['Sri Lanka','Sri Jayawardenepura Kotte']
		,['Sweden','Stockholm']
		,['Bolivia','Sucre (de jure), 
		La Paz (seat of government)']
		,['Fiji','Suva']
		,['Taiwan','Taipei']
		,['Estonia','Tallinn']
		,['Kiribati','Tarawa']
		,['Uzbekistan','Tashkent']
		,['Georgia','Tbilisi']
		,['Honduras','Tegucigalpa']
		,['Iran','Tehran']
		,['Bhutan','Thimphu']
		,['Albania','Tirana']
		,['Japan','Tokyo']
		,['Libya','Tripoli']
		,['Tunisia','Tunis']
		,['Mongolia','Ulaanbaatar']
		,['Liechtenstein','Vaduz']
		,['Malta','Valletta']
		,['Vatican City (Holy See)','Vatican City']
		,['Seychelles','Victoria']
		,['Austria','Vienna']
		,['Laos','Vientiane']
		,['Lithuania','Vilnius']
		,['Poland','Warsaw']
		,['United States of America','Washington, D.C.']
		,['New Zealand','Wellington']
		,['Namibia','Windhoek']
		,['Cote d\'Ivoire','Yamoussoukro']
		,['Cameroon','Yaounde']
		,['Nauru','Yaren District (de facto)']
		,['Armenia','Yerevan']
		,['Croatia','Zagreb']
	];

?>